# fly.toml file generated for eagle-overlord on 2022-07-07T08:51:38-07:00

app = "eagle-overlord"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[experimental]
  cmd = ["node","dist/src/main.js"]
